apiVersion: v1
kind: Namespace
metadata:
  name: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: amgademad/app:vtag
          ports:
            - name: http
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: app
spec:
  selector: 
    app: node-app
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
